In [1]:
n = int(input("Enter the range: "))

Enter the range: 10000

In [2]:
import pandas
import math
df = pandas.DataFrame(columns=['k_val', 'k-2_val', 'min_val'])


def pval(n):
    l = []
    for i in range(5, n+1):
        if i > 1:
            for j in range(2, i):
                if i % j == 0:
                    break
            else:
                l.append(i)
    return(l)

def odd_numbers(n):
    L = []
    for i in range(5, n+1):
        if i % 2 != 0:
            L.append(i)
    return L

def val(l):
    p = []
    for n in l:
        k = n-2
        p.append(k)
    return p


def ro(s):
    d = []
    for n in s:
        l = []
        while n % 2 == 0:
            l.append(2)
            n = n/2
        for i in range(3, int(math.sqrt(n))+1, 2):
            while n % i == 0:
                l.append(i)
                n = n/i
        if n > 2:
            l.append(int(n))
        if l == []:
            pass
        else:
            d.append(min(l))
    return d



c = odd_numbers(n)
# print(c)
s = val(c)
# print(s)
k = ro(s)
# print(k)

df['k_val'] = c
df['k-2_val'] = s
df['min_val'] = k

#df.to_excel("Oddvalue.xlsx")

In [3]:
def check_for_m(n):
    primes = []
    for i in range(2, n+1):
        for j in range(2, i):
            if i % j == 0:
                break
        else:
            primes.append(i)

    for prime in primes:
        if prime == 2:
            continue

        if prime > n:
            break

        if prime in pval(n):
            l = []
            for i in df['k_val'].where(df['min_val'] == prime).values:
                if str(i) != "nan":
                    l.append(i)
            if n in l:
                return "m="+ str(prime)
            else:
                continue

    return "not found"

In [12]:
x = int(input("What is the odd number: "))
while int(x) % 2 == 0:
    print("Error: Input must be an odd number.")
    x = input("Please re-enter the odd number: ")

What is the odd number: 579

In [13]:
def generate_numbers(n):
    nums = [6*k+5 for k in range(1, n+1)]
    nums2= [30*k+7 for k in range(1, n+1)]
    nums3= [84*k-5 for k in range(1, n+1)]
    
    if x in pval(n):
        print("m="+ str (x-2))
    elif x in nums:
        print( "m=3")
    elif x in nums2:
        print( "m=5")
    elif x in nums2:
        print( "m=7")
    else:
        print(check_for_m(x))
        
                         
generate_numbers(n)

m=577

In [3]:
l=[]
for i in df['k_val'].where(df['min_val']==11).values:
    if(str(i) != "nan"):
        l.append(i)

In [4]:
l

[13.0,
 123.0,
 145.0,
 189.0,
 211.0,
 255.0,
 321.0,
 343.0,
 409.0,
 453.0,
 475.0,
 519.0,
 585.0,
 651.0,
 673.0,
 739.0,
 783.0,
 805.0,
 871.0,
 915.0,
 981.0,
 1069.0,
 1113.0,
 1135.0,
 1179.0,
 1201.0,
 1245.0,
 1333.0,
 1399.0,
 1443.0,
 1509.0,
 1531.0,
 1575.0,
 1641.0,
 1663.0,
 1729.0,
 1795.0,
 1839.0,
 1861.0,
 1905.0,
 1971.0,
 1993.0,
 2059.0,
 2103.0,
 2125.0,
 2169.0,
 2191.0,
 2301.0,
 2323.0,
 2433.0,
 2455.0,
 2499.0,
 2521.0,
 2565.0,
 2631.0,
 2653.0,
 2719.0,
 2763.0,
 2785.0,
 2829.0,
 2895.0,
 2961.0,
 2983.0,
 3049.0,
 3093.0,
 3115.0,
 3181.0,
 3225.0,
 3291.0,
 3379.0,
 3423.0,
 3445.0,
 3489.0,
 3511.0,
 3555.0,
 3643.0,
 3709.0,
 3753.0,
 3819.0,
 3841.0,
 3885.0,
 3951.0,
 3973.0,
 4039.0,
 4105.0,
 4149.0,
 4171.0,
 4215.0,
 4281.0,
 4303.0,
 4369.0,
 4413.0,
 4435.0,
 4479.0,
 4501.0,
 4611.0,
 4633.0,
 4743.0,
 4765.0,
 4809.0,
 4831.0,
 4875.0,
 4941.0,
 4963.0,
 5029.0,
 5073.0,
 5095.0,
 5139.0,
 5205.0,
 5271.0,
 5293.0,
 5359.0,
 5403.0,
 5425.0,
 5491.0,
 5535.0,
 5601.0,
 5689.0,
 5733.0,
 5755.0,
 5799.0,
 5821.0,
 5865.0,
 5953.0,
 6019.0,
 6063.0,
 6129.0,
 6151.0,
 6195.0,
 6261.0,
 6283.0,
 6349.0,
 6415.0,
 6459.0,
 6481.0,
 6525.0,
 6591.0,
 6613.0,
 6679.0,
 6723.0,
 6745.0,
 6789.0,
 6811.0,
 6921.0,
 6943.0,
 7053.0,
 7075.0,
 7119.0,
 7141.0,
 7185.0,
 7251.0,
 7273.0,
 7339.0,
 7383.0,
 7405.0,
 7449.0,
 7515.0,
 7581.0,
 7603.0,
 7669.0,
 7713.0,
 7735.0,
 7801.0,
 7845.0,
 7911.0,
 7999.0,
 8043.0,
 8065.0,
 8109.0,
 8131.0,
 8175.0,
 8263.0,
 8329.0,
 8373.0,
 8439.0,
 8461.0,
 8505.0,
 8571.0,
 8593.0,
 8659.0,
 8725.0,
 8769.0,
 8791.0,
 8835.0,
 8901.0,
 8923.0,
 8989.0,
 9033.0,
 9055.0,
 9099.0,
 9121.0,
 9231.0,
 9253.0,
 9363.0,
 9385.0,
 9429.0,
 9451.0,
 9495.0,
 9561.0,
 9583.0,
 9649.0,
 9693.0,
 9715.0,
 9759.0,
 9825.0,
 9891.0,
 9913.0,
 9979.0]